<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Roger Tchegui" />


<title>CaseStudy02.Rmd</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">MyPage</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="aboutme.html">Home</a>
</li>
<li>
  <a href="index.html">other</a>
</li>
<li>
  <a href="FirstCaseStudy.html">case study 1</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">CaseStudy02.Rmd</h1>
<h4 class="author">Roger Tchegui</h4>
<h4 class="date">8/2/2021</h4>

</div>


<pre class="r"><code>## First Question of interest: Answers to Case Study 2 Tasks

###Introduction to this project: DDSAnalytics is an analytics company that specializes in talent management solutions for Fortune 1000 companies. Talent management is defined as the iterative process of developing and retaining employees. It may include workforce planning, employee training programs, identifying high-potential employees and reducing/preventing voluntary employee turnover (attrition). To gain a competitive edge over its competition, DDSAnalytics is planning to leverage data science for talent management. The executive leadership has identified predicting employee turnover as its first application of data science for talent management. Before the business green lights the project, they have tasked your data science team to conduct an analysis of existing employee data.

### Our team has been given a dataset (CaseStudy2-Data.csv) to conduct exploratory data analysis (EDA) to determine factors that lead to attrition. Our goal is to identify (at least) the top three factors that contribute to turnover. Additionally, the business is also interested in learning about any job role specific trends that may exist in the data set.</code></pre>
<pre class="r"><code>## Loading the caseStudy02 data set into r. 
CS  &lt;- read.csv(&#39;C:\\Users\\tcheg\\OneDrive\\Documents\\Doing Data Science 6306\\CaseStudy2-data.csv&#39;,header = TRUE)
head(CS)</code></pre>
<pre><code>##   ID Age Attrition    BusinessTravel DailyRate             Department
## 1  1  32        No     Travel_Rarely       117                  Sales
## 2  2  40        No     Travel_Rarely      1308 Research &amp; Development
## 3  3  35        No Travel_Frequently       200 Research &amp; Development
## 4  4  32        No     Travel_Rarely       801                  Sales
## 5  5  24        No Travel_Frequently       567 Research &amp; Development
## 6  6  27        No Travel_Frequently       294 Research &amp; Development
##   DistanceFromHome Education   EducationField EmployeeCount EmployeeNumber
## 1               13         4    Life Sciences             1            859
## 2               14         3          Medical             1           1128
## 3               18         2    Life Sciences             1           1412
## 4                1         4        Marketing             1           2016
## 5                2         1 Technical Degree             1           1646
## 6               10         2    Life Sciences             1            733
##   EnvironmentSatisfaction Gender HourlyRate JobInvolvement JobLevel
## 1                       2   Male         73              3        2
## 2                       3   Male         44              2        5
## 3                       3   Male         60              3        3
## 4                       3 Female         48              3        3
## 5                       1 Female         32              3        1
## 6                       4   Male         32              3        3
##                  JobRole JobSatisfaction MaritalStatus MonthlyIncome
## 1        Sales Executive               4      Divorced          4403
## 2      Research Director               3        Single         19626
## 3 Manufacturing Director               4        Single          9362
## 4        Sales Executive               4       Married         10422
## 5     Research Scientist               4        Single          3760
## 6 Manufacturing Director               1      Divorced          8793
##   MonthlyRate NumCompaniesWorked Over18 OverTime PercentSalaryHike
## 1        9250                  2      Y       No                11
## 2       17544                  1      Y       No                14
## 3       19944                  2      Y       No                11
## 4       24032                  1      Y       No                19
## 5       17218                  1      Y      Yes                13
## 6        4809                  1      Y       No                21
##   PerformanceRating RelationshipSatisfaction StandardHours StockOptionLevel
## 1                 3                        3            80                1
## 2                 3                        1            80                0
## 3                 3                        3            80                0
## 4                 3                        3            80                2
## 5                 3                        3            80                0
## 6                 4                        3            80                2
##   TotalWorkingYears TrainingTimesLastYear WorkLifeBalance YearsAtCompany
## 1                 8                     3               2              5
## 2                21                     2               4             20
## 3                10                     2               3              2
## 4                14                     3               3             14
## 5                 6                     2               3              6
## 6                 9                     4               2              9
##   YearsInCurrentRole YearsSinceLastPromotion YearsWithCurrManager
## 1                  2                       0                    3
## 2                  7                       4                    9
## 3                  2                       2                    2
## 4                 10                       5                    7
## 5                  3                       1                    3
## 6                  7                       1                    7</code></pre>
<pre class="r"><code>## Loading the various packages that will be use to conduct this study 
library(ggplot2)</code></pre>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.0.5</code></pre>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 4.0.5</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## Warning: package &#39;tidyverse&#39; was built under R version 4.0.5</code></pre>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
<pre><code>## v tibble  3.1.1     v purrr   0.3.4
## v tidyr   1.1.3     v stringr 1.4.0
## v readr   1.4.0     v forcats 0.5.1</code></pre>
<pre><code>## Warning: package &#39;tibble&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Warning: package &#39;readr&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Warning: package &#39;purrr&#39; was built under R version 4.0.3</code></pre>
<pre><code>## Warning: package &#39;stringr&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Warning: package &#39;forcats&#39; was built under R version 4.0.5</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(MASS)</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<pre class="r"><code>library(caret)</code></pre>
<pre><code>## Warning: package &#39;caret&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<pre class="r"><code>library(car)</code></pre>
<pre><code>## Warning: package &#39;car&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## Warning: package &#39;carData&#39; was built under R version 4.0.3</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre class="r"><code>library(&quot;randomForest&quot;)</code></pre>
<pre><code>## Warning: package &#39;randomForest&#39; was built under R version 4.0.5</code></pre>
<pre><code>## randomForest 4.6-14</code></pre>
<pre><code>## Type rfNews() to see new features/changes/bug fixes.</code></pre>
<pre><code>## 
## Attaching package: &#39;randomForest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     combine</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     margin</code></pre>
<pre class="r"><code>library(randomForest)
##install.packages(&quot;cowplot&quot;)
library(cowplot)</code></pre>
<pre><code>## Warning: package &#39;cowplot&#39; was built under R version 4.0.5</code></pre>
<pre class="r"><code>##install.packages(&quot;leaps&quot;)
library(leaps)</code></pre>
<pre><code>## Warning: package &#39;leaps&#39; was built under R version 4.0.5</code></pre>
<pre class="r"><code>library(e1071)</code></pre>
<pre><code>## Warning: package &#39;e1071&#39; was built under R version 4.0.5</code></pre>
<pre class="r"><code>library(ROSE)</code></pre>
<pre><code>## Warning: package &#39;ROSE&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Loaded ROSE 0.0-4</code></pre>
<pre class="r"><code>library(fastDummies)</code></pre>
<pre><code>## Warning: package &#39;fastDummies&#39; was built under R version 4.0.5</code></pre>
<pre class="r"><code>library(caret)
library(class)</code></pre>
<pre><code>## Warning: package &#39;class&#39; was built under R version 4.0.5</code></pre>
<pre class="r"><code>## We will first convert some of our columns into percentage

CS %&gt;% group_by(Attrition)%&gt;%count(Department)%&gt;% mutate(perc = n/nrow(CS)) -&gt; CS_perc

## Let&#39;s plot department column versus Attrition. 

CS_perc%&gt;% ggplot(aes(x=Department, y=perc))+ geom_bar(stat=&quot;identity&quot;) + facet_grid(~Attrition)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>## Conclusion: It appears that Research &amp; Development and Sales have the highest rate of Attrition</p>
<pre class="r"><code>## Let&#39;s now Convert the Gender column into percent to see at which rate male and female leave the organization. 

CS %&gt;% group_by(Attrition)%&gt;%count(Gender)%&gt;%mutate(perc =n/nrow(CS)) -&gt; CS_G
CS_G%&gt;% ggplot(aes(x = Gender, y = perc)) + geom_bar(stat = &quot;identity&quot;) + facet_grid(~Attrition)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = CS, aes(x = MonthlyIncome , y = Gender)) +  geom_boxplot() + coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>CS %&gt;%group_by(JobSatisfaction) %&gt;% count(JobRole) %&gt;% mutate(perc = n/nrow(CS)) -&gt;CS_job
CS_job %&gt;% ggplot(aes(x =JobRole, y=perc)) + geom_bar(stat = &#39;identity&#39;) + facet_wrap(~JobSatisfaction)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-5-3.png" width="672" /></p>
<pre class="r"><code>CS %&gt;% ggplot((aes(x= BusinessTravel)))+geom_bar() +  facet_grid(~Attrition)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = CS, aes( x= MonthlyIncome, y=BusinessTravel)) + geom_boxplot() + coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<div id="conclusion-the-analysis-of-the-barplot-show-that-male-leave-the-organization-more-than-female." class="section level2">
<h2>Conclusion: The analysis of the barplot Show that male leave the organization more than female.</h2>
<pre class="r"><code>CS %&gt;% ggplot((aes(x= MaritalStatus)))+geom_bar() +  facet_grid(~Attrition)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = CS, aes( x= MonthlyIncome, y=MaritalStatus)) + geom_boxplot() + coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre class="r"><code>CS %&gt;% ggplot(aes(x=MonthlyIncome, y=Attrition)) + geom_boxplot()+ coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>## Let&#39;s now look at the MonthlyIncome Versus Attrition. 

CS %&gt;% group_by(Attrition) %&gt;% count(MonthlyIncome)%&gt;% mutate(perc  = n/nrow(CS)) -&gt; CS_M
CS %&gt;% ggplot(aes(x = MonthlyIncome, y = Attrition))  + geom_boxplot() + coord_flip() </code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>CS %&gt;% ggplot(aes(x=MonthlyIncome, y=Attrition)) + geom_boxplot()+ coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>CS %&gt;% ggplot(aes(x=MonthlyRate, y= Attrition)) + geom_boxplot()+ facet_wrap(~Gender) + coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<pre class="r"><code>CS %&gt;% ggplot(aes(x=Attrition, y=Age))  + geom_boxplot()+ facet_wrap(~Gender)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-10-3.png" width="672" /></p>
<pre class="r"><code>CS %&gt;% ggplot(aes(x=MaritalStatus))  + geom_bar()+ facet_wrap(~Attrition)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-10-4.png" width="672" /></p>
<pre class="r"><code>CS %&gt;% ggplot(aes(x=ID, y=Attrition)) + geom_boxplot()+ coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-10-5.png" width="672" /></p>
<pre class="r"><code>CS %&gt;% ggplot(aes(x=Age, y=Attrition)) + geom_boxplot()+ coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-10-6.png" width="672" /></p>
<pre class="r"><code>hist(CS$MonthlyIncome, main = &quot;Monthly Income&quot;)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>hist(CS$MonthlyRate, main = &quot;Monthly Rate&quot;)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>boxplot(CS$DailyRate ~ CS$Attrition, 
        ylab = &quot;Dollars&quot;,
        main = &quot;Hourly Rate by Attrition&quot;)</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="conclusion-the-analysis-of-the-boxplot-show-that-people-making-less-moeny-than-the-median-income-leave-the-organization-the-most" class="section level2">
<h2>Conclusion: The analysis of the boxplot show that people making less moeny than the median Income leave the organization the most</h2>
<pre class="r"><code>## We will now look at the Age Versus Attrition 

CS %&gt;% ggplot(aes(x= Age, y = Attrition)) + geom_boxplot() + coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="the-analysis-of-the-boxplot-show-that-younger-workers-leave-the-organization-more-than-older-workers" class="section level2">
<h2>The analysis of the boxplot show that younger workers leave the organization more than older workers</h2>
<pre class="r"><code>## Which role has more chance to leave the organization ( Research Scientist and Laboratory technician has more attrition rate)

CS %&gt;% filter(Department == &quot;Research &amp; Development&quot;) %&gt;% group_by(Attrition) %&gt;% count(JobRole) %&gt;% mutate(perc = n/nrow(CS))-&gt; CS2_perc
CS2_perc %&gt;% ggplot(aes(x=JobRole, y=perc)) + geom_bar(stat=&#39;identity&#39;) +  facet_grid(~Attrition)+coord_flip()</code></pre>
<p><img src="CaseStudy02_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="conclusion-research-scientist-and-laboratory-technician-leave-the-organization-the-most." class="section level2">
<h2>Conclusion: Research Scientist and Laboratory technician leave the organization the most.</h2>
<pre class="r"><code>## Answer to our fist question of interest : Base on the above analysis it appears that top 3 factors leading to Attrition are: 

##- MonthlyIncome
##- Joblevel 
##- Age </code></pre>
<pre class="r"><code>## We will next do a further analysis of our data and build a model for identifying attrition, provide a model that will attain at least 60% sensitivity and specificity (60 each = 120 total) for the training and the validation set

## Let&#39;s first check if our data are balance, in other for us to have a non-bias model our data need to be balance 
# table(data$Attrition)</code></pre>
</div>
<div id="conclusion-the-analysis-of-the-attrition-column-show-that-we-have-more-no-than-yes-meaning-our-data-are-not-balance." class="section level2">
<h2>Conclusion: The analysis of the Attrition column show that we have more “No” than “Yes” meaning our data are not balance.</h2>
<pre class="r"><code>## Let&#39;s now balance our data 

data &lt;- CS
data_balanced_over &lt;- ovun.sample(Attrition ~ ., data = data, method = &quot;over&quot;,p=0.5,seed=1)$data
table(data_balanced_over$Attrition)</code></pre>
<pre><code>## 
##  No Yes 
## 730 693</code></pre>
<pre class="r"><code>## We will then scale our data and convert it into numerical variables before building our model. 

data_balanced_over_scaled &lt;- data_balanced_over
data_balanced_over_scaled[,c(&quot;Age&quot;,&quot;DailyRate&quot;,&quot;DistanceFromHome&quot;,&quot;Education&quot;,&quot;EnvironmentSatisfaction&quot;,&quot;HourlyRate&quot;,&quot;JobInvolvement&quot;,&quot;JobLevel&quot;,&quot;JobSatisfaction&quot;,&quot;MonthlyIncome&quot;,&quot;MonthlyRate&quot;,&quot;NumCompaniesWorked&quot;,&quot;PercentSalaryHike&quot;,&quot;PerformanceRating&quot;,&quot;RelationshipSatisfaction&quot;,&quot;StockOptionLevel&quot;,&quot;TotalWorkingYears&quot;,&quot;TrainingTimesLastYear&quot;,&quot;WorkLifeBalance&quot;,&quot;YearsAtCompany&quot;,&quot;YearsInCurrentRole&quot;,&quot;YearsSinceLastPromotion&quot;,&quot;YearsWithCurrManager&quot;)] &lt;- scale(data_balanced_over_scaled[,c(&quot;Age&quot;,&quot;DailyRate&quot;,&quot;DistanceFromHome&quot;,&quot;Education&quot;,&quot;EnvironmentSatisfaction&quot;,&quot;HourlyRate&quot;,&quot;JobInvolvement&quot;,&quot;JobLevel&quot;,&quot;JobSatisfaction&quot;,&quot;MonthlyIncome&quot;,&quot;MonthlyRate&quot;,&quot;NumCompaniesWorked&quot;,&quot;PercentSalaryHike&quot;,&quot;PerformanceRating&quot;,
            &quot;RelationshipSatisfaction&quot;,&quot;StockOptionLevel&quot;,&quot;TotalWorkingYears&quot;,&quot;TrainingTimesLastYear&quot;,&quot;WorkLifeBalance&quot;,&quot;YearsAtCompany&quot;,&quot;YearsInCurrentRole&quot;,&quot;YearsSinceLastPromotion&quot;,&quot;YearsWithCurrManager&quot;)])


data_balanced_over_scaled$Attrition &lt;- as.factor(data_balanced_over_scaled$Attrition)
data_balanced_over_scaled$Gender &lt;- as.factor(data_balanced_over_scaled$Gender)
data_balanced_over_scaled$BusinessTravel &lt;- as.factor(data_balanced_over_scaled$BusinessTravel)
data_balanced_over_scaled$Over18 &lt;- as.factor(data_balanced_over_scaled$Over18)
data_balanced_over_scaled$OverTime &lt;- as.factor(data_balanced_over_scaled$OverTime)
data_balanced_over_scaled$MaritalStatus &lt;- as.factor(data_balanced_over_scaled$MaritalStatus)
data_balanced_over_scaled$Department &lt;- as.factor(data_balanced_over_scaled$Department)
data_balanced_over_scaled$EducationField &lt;- as.factor(data_balanced_over_scaled$EducationField)
data_balanced_over_scaled$JobRole &lt;- as.factor(data_balanced_over_scaled$JobRole)


data_balanced_over_scaled$Attrition &lt;- ifelse(data_balanced_over_scaled$Attrition ==&quot;No&quot;,0,1)
data_balanced_over_scaled$Gender &lt;- ifelse(data_balanced_over_scaled$Gender== &quot;Male&quot;,1,0)
data_balanced_over_scaled$Over18 &lt;- ifelse(data_balanced_over_scaled$Over18==&quot;No&quot;,0,1)
data_balanced_over_scaled$OverTime &lt;- ifelse(data_balanced_over_scaled$OverTime==&quot;No&quot;,0,1)

data_balanced_over_scaled &lt;- dummy_cols(data_balanced_over_scaled, select_columns = c(&quot;BusinessTravel&quot;,&quot;Department&quot;,&quot;EducationField&quot;,&quot;JobRole&quot;,&quot;MaritalStatus&quot;), remove_first_dummy = TRUE)

str(data_balanced_over_scaled)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1423 obs. of  55 variables:
##  $ ID                               : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Age                              : num  -0.413 0.454 -0.088 -0.413 -1.28 ...
##  $ Attrition                        : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ BusinessTravel                   : Factor w/ 3 levels &quot;Non-Travel&quot;,&quot;Travel_Frequently&quot;,..: 3 3 2 3 2 2 3 3 3 2 ...
##  $ DailyRate                        : num  -1.69973 1.26741 -1.49295 0.00432 -0.57865 ...
##  $ Department                       : Factor w/ 3 levels &quot;Human Resources&quot;,..: 3 2 2 3 2 2 2 3 3 2 ...
##  $ DistanceFromHome                 : num  0.326 0.443 0.911 -1.078 -0.961 ...
##  $ Education                        : num  1.114 0.128 -0.858 1.114 -1.844 ...
##  $ EducationField                   : Factor w/ 6 levels &quot;Human Resources&quot;,..: 2 4 2 3 6 2 4 2 2 6 ...
##  $ EmployeeCount                    : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ EmployeeNumber                   : int  859 1128 1412 2016 1646 733 1448 1105 1055 1597 ...
##  $ EnvironmentSatisfaction          : num  -0.566 0.32 0.32 0.32 -1.452 ...
##  $ Gender                           : num  1 1 1 0 0 1 1 0 0 1 ...
##  $ HourlyRate                       : num  0.333 -1.115 -0.316 -0.915 -1.714 ...
##  $ JobInvolvement                   : num  0.511 -0.787 0.511 0.511 0.511 ...
##  $ JobLevel                         : num  0.0599 2.8416 0.9871 0.9871 -0.8673 ...
##  $ JobRole                          : Factor w/ 9 levels &quot;Healthcare Representative&quot;,..: 8 6 5 8 7 5 7 8 9 1 ...
##  $ JobSatisfaction                  : num  1.223 0.331 1.223 1.223 1.223 ...
##  $ MaritalStatus                    : Factor w/ 3 levels &quot;Divorced&quot;,&quot;Married&quot;,..: 1 3 3 2 3 1 2 1 2 2 ...
##  $ MonthlyIncome                    : num  -0.345 3.08 0.771 1.009 -0.49 ...
##  $ MonthlyRate                      : num  -0.71 0.446 0.78 1.349 0.4 ...
##  $ NumCompaniesWorked               : num  -0.322 -0.706 -0.322 -0.706 -0.706 ...
##  $ Over18                           : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ OverTime                         : num  0 0 0 0 1 0 1 1 1 0 ...
##  $ PercentSalaryHike                : num  -1.12 -0.323 -1.12 1.004 -0.589 ...
##  $ PerformanceRating                : num  -0.432 -0.432 -0.432 -0.432 -0.432 ...
##  $ RelationshipSatisfaction         : num  0.286 -1.478 0.286 0.286 0.286 ...
##  $ StandardHours                    : int  80 80 80 80 80 80 80 80 80 80 ...
##  $ StockOptionLevel                 : num  0.367 -0.76 -0.76 1.493 -0.76 ...
##  $ TotalWorkingYears                : num  -0.2901 1.4538 -0.0218 0.5148 -0.5583 ...
##  $ TrainingTimesLastYear            : num  0.208 -0.598 -0.598 0.208 -0.598 ...
##  $ WorkLifeBalance                  : num  -0.96 1.705 0.373 0.373 0.373 ...
##  $ YearsAtCompany                   : num  -0.2452 2.1819 -0.7306 1.2111 -0.0833 ...
##  $ YearsInCurrentRole               : num  -0.514 0.879 -0.514 1.715 -0.235 ...
##  $ YearsSinceLastPromotion          : num  -0.6866 0.5067 -0.0899 0.8051 -0.3883 ...
##  $ YearsWithCurrManager             : num  -0.232 1.473 -0.517 0.905 -0.232 ...
##  $ BusinessTravel_Travel_Frequently : int  0 0 1 0 1 1 0 0 0 1 ...
##  $ BusinessTravel_Travel_Rarely     : int  1 1 0 1 0 0 1 1 1 0 ...
##  $ Department_Research &amp; Development: int  0 1 1 0 1 1 1 0 0 1 ...
##  $ Department_Sales                 : int  1 0 0 1 0 0 0 1 1 0 ...
##  $ EducationField_Life Sciences     : int  1 0 1 0 0 1 0 1 1 0 ...
##  $ EducationField_Marketing         : int  0 0 0 1 0 0 0 0 0 0 ...
##  $ EducationField_Medical           : int  0 1 0 0 0 0 1 0 0 0 ...
##  $ EducationField_Other             : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ EducationField_Technical Degree  : int  0 0 0 0 1 0 0 0 0 1 ...
##  $ JobRole_Human Resources          : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ JobRole_Laboratory Technician    : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ JobRole_Manager                  : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ JobRole_Manufacturing Director   : int  0 0 1 0 0 1 0 0 0 0 ...
##  $ JobRole_Research Director        : int  0 1 0 0 0 0 0 0 0 0 ...
##  $ JobRole_Research Scientist       : int  0 0 0 0 1 0 1 0 0 0 ...
##  $ JobRole_Sales Executive          : int  1 0 0 1 0 0 0 1 0 0 ...
##  $ JobRole_Sales Representative     : int  0 0 0 0 0 0 0 0 1 0 ...
##  $ MaritalStatus_Married            : int  0 0 0 1 0 0 1 0 1 1 ...
##  $ MaritalStatus_Single             : int  0 1 1 0 1 0 0 0 0 0 ...</code></pre>
<pre class="r"><code>data_balanced_over_scaled &lt;- data_balanced_over_scaled %&gt;% dplyr::select(-one_of(c(&quot;BusinessTravel&quot;,&quot;Department&quot;,&quot;EducationField&quot;,&quot;JobRole&quot;,&quot;MaritalStatus&quot;,&quot;ID&quot;,&quot;StandardHours&quot;,&quot;EmployeeCount&quot;,&quot;EmployeeNumber&quot;)))


## We now ready to build our model to predict attrition: We will be using KNN model

Target &lt;- data_balanced_over_scaled %&gt;% dplyr::select(one_of(&quot;Attrition&quot;))
Predictors &lt;- data_balanced_over_scaled %&gt;% dplyr::select(-one_of(&quot;Attrition&quot;))
split_perc = .7
split_index &lt;- sample(dim(Predictors)[1], round(dim(Predictors)[1]*split_perc))
Predictors_Train &lt;- Predictors[split_index,]
Predictors_Test &lt;- Predictors[-split_index,]
Target_Train &lt;- Target[split_index,]
Target_Test &lt;- Target[-split_index,]
classifications &lt;- knn(Predictors_Train,Predictors_Test , as.factor(Target_Train),k=5,prob=T)
table(classifications, as.factor(Target_Test))</code></pre>
<pre><code>##                
## classifications   0   1
##               0 146  33
##               1  83 165</code></pre>
<pre class="r"><code>cm &lt;- confusionMatrix(classifications,as.factor(Target_Test))
print(cm)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 146  33
##          1  83 165
##                                         
##                Accuracy : 0.7283        
##                  95% CI : (0.6835, 0.77)
##     No Information Rate : 0.5363        
##     P-Value [Acc &gt; NIR] : 2.985e-16     
##                                         
##                   Kappa : 0.463         
##                                         
##  Mcnemar&#39;s Test P-Value : 5.376e-06     
##                                         
##             Sensitivity : 0.6376        
##             Specificity : 0.8333        
##          Pos Pred Value : 0.8156        
##          Neg Pred Value : 0.6653        
##              Prevalence : 0.5363        
##          Detection Rate : 0.3419        
##    Detection Prevalence : 0.4192        
##       Balanced Accuracy : 0.7354        
##                                         
##        &#39;Positive&#39; Class : 0             
## </code></pre>
</div>
<div id="conclusion-with-the-above-model-we-were-able-to-get-the-acuracy-of-0.7283-the-sensitivity-of-0.6376-and-tyhe-specificity-of-0.8333" class="section level2">
<h2>Conclusion : With the above model we were able to get the acuracy of 0.7283, the sensitivity of 0.6376 and tyhe specificity of 0.8333</h2>
<pre class="r"><code>## Let&#39;s now used a different model to predict Attrition: naivesbayes model. 

set.seed(5)
model &lt;- naiveBayes(Predictors_Train, as.factor(Target_Train))
classification &lt;- predict(model,Predictors_Test) 
confusionMatrix(table(classification,as.factor(Target_Test)))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##               
## classification   0   1
##              0 115  32
##              1 114 166
##                                          
##                Accuracy : 0.6581         
##                  95% CI : (0.6109, 0.703)
##     No Information Rate : 0.5363         
##     P-Value [Acc &gt; NIR] : 2.196e-07      
##                                          
##                   Kappa : 0.3313         
##                                          
##  Mcnemar&#39;s Test P-Value : 2.033e-11      
##                                          
##             Sensitivity : 0.5022         
##             Specificity : 0.8384         
##          Pos Pred Value : 0.7823         
##          Neg Pred Value : 0.5929         
##              Prevalence : 0.5363         
##          Detection Rate : 0.2693         
##    Detection Prevalence : 0.3443         
##       Balanced Accuracy : 0.6703         
##                                          
##        &#39;Positive&#39; Class : 0              
## </code></pre>
</div>
<div id="conclusion-the-naivesbayes-model-give-us-well-above-6060-sensitivity-and-specificity" class="section level2">
<h2>Conclusion: The naivesbayes model give us well above 60/60 sensitivity and specificity</h2>
<pre class="r"><code>## Let&#39;s build our linear regression model to predict our RMSE

## We will have to reconvert our data again and store it into a new data frame 

data_balanced_ove_scaled2 &lt;- data_balanced_over
data_balanced_ove_scaled2$Attrition &lt;- as.factor(data_balanced_ove_scaled2$Attrition)
data_balanced_ove_scaled2$Gender &lt;- as.factor(data_balanced_ove_scaled2$Gender)
data_balanced_ove_scaled2$BusinessTravel &lt;- as.factor(data_balanced_ove_scaled2$BusinessTravel)
data_balanced_ove_scaled2$Over18 &lt;- as.factor(data_balanced_ove_scaled2$Over18)
data_balanced_ove_scaled2$OverTime &lt;- as.factor(data_balanced_ove_scaled2$OverTime)
data_balanced_ove_scaled2$MaritalStatus &lt;- as.factor(data_balanced_ove_scaled2$MaritalStatus)
data_balanced_ove_scaled2$Department &lt;- as.factor(data_balanced_ove_scaled2$Department)
data_balanced_ove_scaled2$EducationField &lt;- as.factor(data_balanced_ove_scaled2$EducationField)
data_balanced_ove_scaled2$JobRole &lt;- as.factor(data_balanced_ove_scaled2$JobRole)


data_balanced_ove_scaled2$Attrition &lt;- ifelse(data_balanced_ove_scaled2$Attrition ==&quot;No&quot;,0,1)
data_balanced_ove_scaled2$Gender &lt;- ifelse(data_balanced_ove_scaled2$Gender== &quot;Male&quot;,1,0)
data_balanced_ove_scaled2$Over18 &lt;- ifelse(data_balanced_ove_scaled2$Over18==&quot;No&quot;,0,1)
data_balanced_ove_scaled2$OverTime &lt;- ifelse(data_balanced_ove_scaled2$OverTime==&quot;No&quot;,0,1)


data_balanced_ove_scaled2 &lt;- dummy_cols(data_balanced_ove_scaled2, select_columns = c(&quot;BusinessTravel&quot;,&quot;Department&quot;,&quot;EducationField&quot;,&quot;JobRole&quot;,&quot;MaritalStatus&quot;), remove_first_dummy = TRUE)




data_balanced_ove_scaled2[,c(&quot;Age&quot;,&quot;DailyRate&quot;,&quot;DistanceFromHome&quot;,&quot;Education&quot;,&quot;EnvironmentSatisfaction&quot;,&quot;HourlyRate&quot;,&quot;JobInvolvement&quot;,&quot;JobLevel&quot;,
                      &quot;JobSatisfaction&quot;,&quot;MonthlyRate&quot;,&quot;NumCompaniesWorked&quot;,&quot;PercentSalaryHike&quot;,&quot;PerformanceRating&quot;,
                      &quot;RelationshipSatisfaction&quot;,&quot;StockOptionLevel&quot;,&quot;TotalWorkingYears&quot;,&quot;TrainingTimesLastYear&quot;,&quot;WorkLifeBalance&quot;,
                      &quot;YearsAtCompany&quot;,&quot;YearsInCurrentRole&quot;,&quot;YearsSinceLastPromotion&quot;,&quot;YearsWithCurrManager&quot;)] &lt;- scale(data_balanced_ove_scaled2[,c(&quot;Age&quot;,&quot;DailyRate&quot;,
                                                                                                                                              &quot;DistanceFromHome&quot;,&quot;Education&quot;,
                                                                                                                                              &quot;EnvironmentSatisfaction&quot;,&quot;HourlyRate&quot;,&quot;JobInvolvement&quot;,
                                                                                                                                              &quot;JobLevel&quot;,&quot;JobSatisfaction&quot;,&quot;MonthlyRate&quot;,
                                                                                                                                              &quot;NumCompaniesWorked&quot;,&quot;PercentSalaryHike&quot;,&quot;PerformanceRating&quot;,
                                                                                                                                               &quot;RelationshipSatisfaction&quot;,&quot;StockOptionLevel&quot;,&quot;TotalWorkingYears&quot;,
                                                                                                                                              &quot;TrainingTimesLastYear&quot;,&quot;WorkLifeBalance&quot;,&quot;YearsAtCompany&quot;,
                                                                                                                                              &quot;YearsInCurrentRole&quot;,&quot;YearsSinceLastPromotion&quot;,&quot;YearsWithCurrManager&quot;)])
data_balanced_ove_scaled2 &lt;- data_balanced_ove_scaled2 %&gt;% dplyr::select(-one_of( c(&quot;BusinessTravel&quot;,&quot;Department&quot;,&quot;EducationField&quot;,&quot;JobRole&quot;,&quot;MaritalStatus&quot;,&quot;EmployeeCount&quot;,&quot;Over18&quot;,&quot;StandardHours&quot;)))


## We now ready to build our linear regression model and predict our RMSE

split_perc = 0.7
split_index &lt;- sample(dim(data_balanced_ove_scaled2)[1], round(dim(data_balanced_ove_scaled2)[1]*split_perc))
MonthlyIncome_LM_train &lt;- data_balanced_ove_scaled2[split_index,]
MonthlyIncome_LM_Test &lt;- data_balanced_ove_scaled2[-split_index,]
linear_model &lt;- lm(MonthlyIncome~., data = MonthlyIncome_LM_train)
summary(linear_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = MonthlyIncome ~ ., data = MonthlyIncome_LM_train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3223.7  -607.6   -60.3   563.9  3910.7 
## 
## Coefficients:
##                                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                         5141.80867  572.74507   8.977  &lt; 2e-16 ***
## ID                                    -0.40624    0.13602  -2.987 0.002894 ** 
## Age                                   -6.14069   46.68487  -0.132 0.895380    
## Attrition                              2.94134   84.96556   0.035 0.972392    
## DailyRate                            125.17783   34.05984   3.675 0.000251 ***
## DistanceFromHome                    -108.86842   34.59235  -3.147 0.001700 ** 
## Education                            -39.22702   34.66481  -1.132 0.258085    
## EmployeeNumber                         0.09489    0.05704   1.664 0.096534 .  
## EnvironmentSatisfaction               56.81287   33.83445   1.679 0.093453 .  
## Gender                                46.88452   70.32856   0.667 0.505158    
## HourlyRate                            -1.68829   34.55018  -0.049 0.961037    
## JobInvolvement                       -28.13646   35.26491  -0.798 0.425151    
## JobLevel                            2893.98259   87.75198  32.979  &lt; 2e-16 ***
## JobSatisfaction                       30.46605   35.17962   0.866 0.386701    
## MonthlyRate                          -53.93490   33.51436  -1.609 0.107882    
## NumCompaniesWorked                    13.86327   40.26658   0.344 0.730707    
## OverTime                              -1.05497   74.30604  -0.014 0.988675    
## PercentSalaryHike                     16.04853   53.78122   0.298 0.765460    
## PerformanceRating                    -58.72467   53.45888  -1.099 0.272264    
## RelationshipSatisfaction              70.55468   34.62319   2.038 0.041848 *  
## StockOptionLevel                     -36.58060   44.84696  -0.816 0.414890    
## TotalWorkingYears                    331.98637   79.38565   4.182 3.16e-05 ***
## TrainingTimesLastYear                 41.42960   33.87423   1.223 0.221618    
## WorkLifeBalance                      -29.76264   34.38251  -0.866 0.386910    
## YearsAtCompany                        80.89934   79.92725   1.012 0.311719    
## YearsInCurrentRole                   -12.69342   60.10191  -0.211 0.832778    
## YearsSinceLastPromotion              172.74447   49.52379   3.488 0.000509 ***
## YearsWithCurrManager                -146.37223   57.79560  -2.533 0.011483 *  
## BusinessTravel_Travel_Frequently     233.60154  144.47571   1.617 0.106234    
## BusinessTravel_Travel_Rarely         499.05694  126.56651   3.943 8.64e-05 ***
## `Department_Research &amp; Development`  366.78082  554.89981   0.661 0.508782    
## Department_Sales                     -84.38971  572.75505  -0.147 0.882895    
## `EducationField_Life Sciences`      -141.33461  362.08047  -0.390 0.696373    
## EducationField_Marketing             177.10757  376.64471   0.470 0.638303    
## EducationField_Medical              -185.76870  361.42353  -0.514 0.607377    
## EducationField_Other                -403.74778  385.10528  -1.048 0.294717    
## `EducationField_Technical Degree`    -65.10208  371.39270  -0.175 0.860888    
## `JobRole_Human Resources`           -116.30381  577.99092  -0.201 0.840569    
## `JobRole_Laboratory Technician`     -745.01400  170.11559  -4.379 1.32e-05 ***
## JobRole_Manager                     4421.46990  270.37627  16.353  &lt; 2e-16 ***
## `JobRole_Manufacturing Director`     296.82010  178.96753   1.659 0.097544 .  
## `JobRole_Research Director`         4173.82354  227.64203  18.335  &lt; 2e-16 ***
## `JobRole_Research Scientist`        -321.83498  171.87729  -1.872 0.061449 .  
## `JobRole_Sales Executive`            399.74529  364.65839   1.096 0.273261    
## `JobRole_Sales Representative`      -261.21361  386.71959  -0.675 0.499548    
## MaritalStatus_Married                140.55544  100.57332   1.398 0.162577    
## MaritalStatus_Single                  95.30431  127.73576   0.746 0.455789    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1017 on 949 degrees of freedom
## Multiple R-squared:  0.9477, Adjusted R-squared:  0.9451 
## F-statistic: 373.5 on 46 and 949 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>Target1 &lt;- MonthlyIncome_LM_Test%&gt;% dplyr::select(one_of(&quot;MonthlyIncome&quot;))
Predictors1 &lt;- MonthlyIncome_LM_Test %&gt;% dplyr:: select(-one_of(&quot;MonthlyIncome&quot;))
predictions &lt;- linear_model %&gt;% predict(MonthlyIncome_LM_Test)

## Let&#39;s find our RMSE


RMSE(predictions, MonthlyIncome_LM_Test$MonthlyIncome)</code></pre>
<pre><code>## [1] 1057.64</code></pre>
</div>
<div id="conclusion-with-the-above-linear-regression-model-we-were-able-to-predict-a-rmse-of-1039.964-well-below-the-require-rmse-of-3000-required-by-the-customer." class="section level2">
<h2>Conclusion: With the above linear regression model we were able to predict a RMSE of 1039.964 well below the require RMSE of &lt; 3000 required by the customer.</h2>
<p>```</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
